export type PlatformRouteEntry = {
  title: string;
  description: string;
  href: string;
  category: string;
  keywords: string[];
};

export const PLATFORM_ROUTE_REGISTRY: PlatformRouteEntry[] = [
  {
    title: "Home",
    description: "Open your personal Loombus Signal hub and workspace shortcuts.",
    href: "/home",
    category: "Core",
    keywords: ["home", "signal hub", "workspace", "start", "shortcuts"],
  },
  {
    title: "Dashboard",
    description: "Review your private account snapshot, goals, and contribution activity.",
    href: "/dashboard",
    category: "Account",
    keywords: ["dashboard", "account home", "goals", "contributions", "status"],
  },
  {
    title: "Discussions",
    description: "Browse the main Loombus public discussion directory.",
    href: "/discussions",
    category: "Core",
    keywords: ["discussions", "threads", "feed", "signal", "conversation"],
  },
  {
    title: "Create discussion",
    description: "Start a focused discussion with a topic, context, lens, and purpose.",
    href: "/create",
    category: "Create",
    keywords: ["create", "post", "write", "draft", "composer", "publish"],
  },
  {
    title: "Topics",
    description: "Browse discussion topics and open a focused Topic Signal page.",
    href: "/topics",
    category: "Explore",
    keywords: ["topics", "topic signal", "categories", "browse", "discover"],
  },
  {
    title: "Advanced search",
    description: "Search discussions, people, saved items, and Loombus destinations.",
    href: "/search",
    category: "Explore",
    keywords: ["search", "advanced search", "find", "lookup", "discover"],
  },
  {
    title: "Local Business and Services",
    description:
      "Browse approved businesses, service areas, and current offerings.",
    href: "/businesses",
    category: "Real-world",
    keywords: [
      "businesses",
      "business directory",
      "local services",
      "companies",
      "contractors",
      "appointments",
    ],
  },
  {
    title: "Jobs Directory",
    description:
      "Browse approved job postings connected to attributable employer profiles.",
    href: "/jobs",
    category: "Real-world",
    keywords: [
      "jobs",
      "hiring",
      "employment",
      "careers",
      "internships",
      "remote jobs",
      "apply",
    ],
  },
  {
    title: "Rooms",
    description: "Open private member workspaces for discussion, announcements, and events.",
    href: "/rooms",
    category: "Spaces",
    keywords: ["rooms", "private rooms", "hoa", "classroom", "teams", "community"],
  },
  {
    title: "People",
    description: "Find Loombus members, profiles, followers, and accounts you follow.",
    href: "/people",
    category: "Network",
    keywords: ["people", "members", "profiles", "followers", "following"],
  },
  {
    title: "Following",
    description: "See discussions and activity from Loombus members you follow.",
    href: "/following",
    category: "Network",
    keywords: ["following", "following feed", "people i follow", "network"],
  },
  {
    title: "Messages",
    description: "Open private conversations with supported Loombus connections.",
    href: "/messages",
    category: "Communication",
    keywords: ["messages", "chat", "inbox", "dm", "private conversations"],
  },
  {
    title: "Notifications",
    description: "Review replies, follows, alerts, messages, and platform activity.",
    href: "/notifications",
    category: "Activity",
    keywords: ["notifications", "alerts", "replies", "follows", "activity", "signal inbox"],
  },
  {
    title: "Saved",
    description: "Return to saved discussions, private notes, folders, and bookmarks.",
    href: "/saved",
    category: "Library",
    keywords: ["saved", "bookmarks", "folders", "notes", "private notes", "library"],
  },
  {
    title: "Stickies",
    description: "Open your private Signal Board of pinned discussion cards.",
    href: "/stickies",
    category: "Workspace",
    keywords: ["stickies", "signal board", "pins", "pinned discussions", "workspace"],
  },
  {
    title: "Profile",
    description: "Review or edit your public identity, bio, avatar, and profile details.",
    href: "/profile",
    category: "Account",
    keywords: ["profile", "bio", "avatar", "identity", "public profile"],
  },
  {
    title: "My Activity",
    description: "Review your discussions, replies, saves, and recent activity.",
    href: "/my-activity",
    category: "Activity",
    keywords: ["my activity", "history", "recent activity", "my contributions"],
  },
  {
    title: "My Discussions",
    description: "Open your published discussions and saved drafts.",
    href: "/my-discussions",
    category: "Activity",
    keywords: ["my discussions", "my posts", "drafts", "published discussions"],
  },
  {
    title: "My Replies",
    description: "Review replies you have written across Loombus.",
    href: "/my-replies",
    category: "Activity",
    keywords: ["my replies", "comments", "responses", "replies i wrote"],
  },
  {
    title: "Reading History",
    description: "Return to discussions you recently opened.",
    href: "/reading-history",
    category: "Library",
    keywords: ["reading history", "recently viewed", "history", "read"],
  },
  {
    title: "Onboarding",
    description: "Resume your Loombus setup and account-starting checklist.",
    href: "/onboarding",
    category: "Account",
    keywords: ["onboarding", "setup", "getting started", "start", "checklist"],
  },
  {
    title: "Settings",
    description: "Manage appearance, account access, privacy, notifications, and preferences.",
    href: "/settings",
    category: "Account",
    keywords: ["settings", "appearance", "privacy", "account", "preferences", "notifications"],
  },
  {
    title: "Privacy & Security",
    description: "Review account privacy, security controls, blocking, and data choices.",
    href: "/privacy-security",
    category: "Account",
    keywords: ["privacy security", "security", "privacy controls", "account protection", "data"],
  },
  {
    title: "Blocked Users",
    description: "Review and manage the members you have blocked.",
    href: "/blocked-users",
    category: "Safety",
    keywords: ["blocked users", "blocks", "unblock", "safety", "privacy"],
  },
  {
    title: "Loombus Guide",
    description: "Learn how current Loombus workspaces, Signal, Rooms, and safety tools work.",
    href: "/settings/guide",
    category: "Help",
    keywords: ["guide", "help", "how to use", "instructions", "signal", "rooms"],
  },
  {
    title: "AI Usage",
    description: "Review AI usage, limits, feature buckets, and recent AI-assisted activity.",
    href: "/ai-usage",
    category: "AI",
    keywords: ["ai", "ai usage", "limits", "meter", "cached", "premium ai"],
  },
  {
    title: "Premium",
    description: "Review subscription options and supported Premium access.",
    href: "/premium",
    category: "Subscription",
    keywords: ["premium", "subscription", "upgrade", "plans", "premium plus"],
  },
  {
    title: "Loombus Labs",
    description: "Request, vote on, and review experimental Loombus features.",
    href: "/labs",
    category: "Build",
    keywords: ["labs", "features", "requests", "vote", "experimental"],
  },
  {
    title: "Support",
    description: "Search Loombus help and submit a structured support request.",
    href: "/support",
    category: "Help",
    keywords: ["support", "help", "contact", "problem", "request"],
  },
  {
    title: "About Loombus",
    description: "Read about Loombus, its purpose, and its Signal-first direction.",
    href: "/about",
    category: "Reference",
    keywords: ["about", "about loombus", "purpose", "mission", "signal over noise"],
  },
  {
    title: "Community Guidelines",
    description: "Review discussion-quality standards and platform expectations.",
    href: "/guidelines",
    category: "Safety",
    keywords: ["guidelines", "community guidelines", "rules", "standards", "conduct"],
  },
  {
    title: "Safety",
    description: "Review reporting, blocking, moderation, and member protections.",
    href: "/safety",
    category: "Safety",
    keywords: ["safety", "reporting", "blocking", "moderation", "protection"],
  },
  {
    title: "Privacy Policy",
    description: "Review how information connected to Loombus is handled.",
    href: "/privacy",
    category: "Legal",
    keywords: ["privacy", "privacy policy", "data", "information", "rights"],
  },
  {
    title: "Cookie Use",
    description: "Review cookies, browser storage, session tokens, and related technologies.",
    href: "/cookies",
    category: "Legal",
    keywords: ["cookies", "cookie use", "browser storage", "session", "tokens"],
  },
  {
    title: "Terms of Service",
    description: "Review the terms that govern access to and use of Loombus.",
    href: "/terms",
    category: "Legal",
    keywords: ["terms", "terms of service", "agreement", "legal", "conditions"],
  },
  {
    title: "Refund Policy",
    description: "Review cancellation and refund rules for supported purchases.",
    href: "/refunds",
    category: "Legal",
    keywords: ["refund", "refund policy", "return policy", "cancellation", "billing"],
  },
  {
    title: "Copyright / DMCA",
    description: "Review copyright reporting and DMCA procedures.",
    href: "/dmca",
    category: "Legal",
    keywords: ["copyright", "dmca", "infringement", "takedown", "rights"],
  },
  {
    title: "Accessibility",
    description: "Review the Loombus accessibility approach and support channel.",
    href: "/accessibility",
    category: "Reference",
    keywords: ["accessibility", "accessible", "disability", "support", "accommodation"],
  },
  {
    title: "Download Loombus",
    description: "Open the Loombus app download page.",
    href: "/download",
    category: "Reference",
    keywords: ["download", "app", "ios", "android", "app store", "google play"],
  },
];
