export type PlatformRouteEntry = {
  title: string;
  description: string;
  href: string;
  category: string;
  keywords: string[];
};

export const PLATFORM_ROUTE_REGISTRY: PlatformRouteEntry[] = [
  {
    title: "Home",
    description: "Open your personal Loombus Signal hub and workspace shortcuts.",
    href: "/home",
    category: "Core",
    keywords: ["home", "signal hub", "workspace", "start", "shortcuts"],
  },
  {
    title: "Dashboard",
    description: "Review your private account snapshot, goals, and contribution activity.",
    href: "/dashboard",
    category: "Account",
    keywords: ["dashboard", "account home", "goals", "contributions", "status"],
  },
  {
    title: "Discussions",
    description: "Browse the main Loombus public discussion directory.",
    href: "/discussions",
    category: "Knowledge",
    keywords: ["discussions", "threads", "feed", "signal", "conversation"],
  },
  {
    title: "Create discussion",
    description:
      "Start a focused discussion with written context, a Topic, Reality Lens, purpose, and supported attachments.",
    href: "/create",
    category: "Create",
    keywords: [
      "create",
      "post",
      "write",
      "draft",
      "composer",
      "publish",
      "video context",
      "attachments",
    ],
  },
  {
    title: "Topics",
    description: "Browse discussion topics and open a focused Topic Signal page.",
    href: "/topics",
    category: "Knowledge",
    keywords: ["topics", "topic signal", "categories", "browse", "discover"],
  },
  {
    title: "Search Everything",
    description:
      "Search authorized Loombus discussions, replies, people, Rooms, saved items, files, real-world listings, and platform destinations.",
    href: "/search",
    category: "Explore",
    keywords: [
      "search",
      "search everything",
      "advanced search",
      "find",
      "lookup",
      "discover",
      "ask loombus ai",
      "grounded answer",
    ],
  },
  {
    title: "Loombus Local",
    description:
      "Discover businesses, Services, Requests, Jobs, Events, Marketplace listings, and remote opportunities by place, distance, date, and availability.",
    href: "/local",
    category: "Real-world",
    keywords: [
      "local",
      "near me",
      "distance",
      "radius",
      "place",
      "remote",
      "business",
      "services",
      "requests",
      "jobs",
      "events",
      "marketplace",
    ],
  },
  {
    title: "Intelligent Matching",
    description:
      "Review private Request-to-Service and Service-to-Request compatibility suggestions.",
    href: "/matches",
    category: "Real-world",
    keywords: [
      "matches",
      "matching",
      "requests",
      "services",
      "compatibility",
      "recommendations",
    ],
  },
  {
    title: "Local Business and Services",
    description:
      "Browse attributable businesses, service areas, and current offerings.",
    href: "/businesses",
    category: "Real-world",
    keywords: [
      "businesses",
      "business directory",
      "local services",
      "companies",
      "contractors",
      "providers",
      "appointments",
    ],
  },
  {
    title: "Services Directory",
    description:
      "Find attributable Services from Loombus members and businesses, send inquiries, connect Requests, and request appointments.",
    href: "/services",
    category: "Real-world",
    keywords: [
      "services",
      "providers",
      "offerings",
      "inquiries",
      "appointments",
      "request service",
      "business services",
    ],
  },
  {
    title: "Requests Directory",
    description:
      "Find public requests for services, recommendations, quotes, consultations, community help, and local problem solving.",
    href: "/requests",
    category: "Real-world",
    keywords: [
      "requests",
      "needs",
      "quotes",
      "consultations",
      "recommendations",
      "community help",
      "problem solving",
    ],
  },
  {
    title: "Appointments",
    description:
      "Manage business appointment services, appointment requests, timing, and status.",
    href: "/appointments",
    category: "Real-world",
    keywords: [
      "appointments",
      "booking",
      "schedule",
      "provider",
      "appointment request",
      "manage appointments",
    ],
  },
  {
    title: "Jobs Directory",
    description:
      "Browse approved job postings connected to attributable employer profiles.",
    href: "/jobs",
    category: "Real-world",
    keywords: [
      "jobs",
      "hiring",
      "employment",
      "careers",
      "internships",
      "remote jobs",
      "apply",
      "employers",
    ],
  },
  {
    title: "Events Directory",
    description:
      "Browse attributable public events and keep real-world or remote dates connected to their organizers.",
    href: "/events",
    category: "Real-world",
    keywords: [
      "events",
      "calendar",
      "organizers",
      "venue",
      "remote events",
      "dates",
      "activities",
    ],
  },
  {
    title: "Marketplace",
    description:
      "Browse approved items from attributable Loombus sellers without sponsored placement or pay-to-rank.",
    href: "/marketplace",
    category: "Real-world",
    keywords: [
      "marketplace",
      "items",
      "seller",
      "buyer",
      "listings",
      "for sale",
      "local marketplace",
    ],
  },
  {
    title: "Rooms",
    description:
      "Open private member workspaces for discussions, announcements, calendars, events, files, forms, and shared coordination.",
    href: "/rooms",
    category: "Spaces",
    keywords: [
      "rooms",
      "private rooms",
      "hoa",
      "classroom",
      "teams",
      "community",
      "calendar",
      "files",
      "forms",
      "polls",
    ],
  },
  {
    title: "People",
    description: "Find Loombus members, profiles, followers, and accounts you follow.",
    href: "/people",
    category: "Network",
    keywords: ["people", "members", "profiles", "followers", "following"],
  },
  {
    title: "Following",
    description: "See discussions and activity from Loombus members you follow.",
    href: "/following",
    category: "Network",
    keywords: ["following", "following feed", "people i follow", "network"],
  },
  {
    title: "Messages",
    description: "Open private conversations with supported Loombus connections.",
    href: "/messages",
    category: "Communication",
    keywords: ["messages", "chat", "inbox", "dm", "private conversations"],
  },
  {
    title: "Notifications",
    description:
      "Review replies, follows, messages, Room activity, reminders, and platform notices.",
    href: "/notifications",
    category: "Activity",
    keywords: [
      "notifications",
      "alerts",
      "replies",
      "follows",
      "activity",
      "signal inbox",
      "push",
      "reminders",
    ],
  },
  {
    title: "Saved",
    description:
      "Return to saved discussions, private notes, folders, and bookmarks.",
    href: "/saved",
    category: "Library",
    keywords: ["saved", "bookmarks", "folders", "notes", "private notes", "library"],
  },
  {
    title: "Stickies",
    description: "Open your private Signal Board of pinned discussion cards.",
    href: "/stickies",
    category: "Workspace",
    keywords: ["stickies", "signal board", "pins", "pinned discussions", "workspace"],
  },
  {
    title: "Profile",
    description: "Review or edit your public identity, bio, avatar, and profile details.",
    href: "/profile",
    category: "Account",
    keywords: ["profile", "bio", "avatar", "identity", "public profile"],
  },
  {
    title: "My Activity",
    description:
      "Review your discussions, replies, saves, and recent activity.",
    href: "/my-activity",
    category: "Activity",
    keywords: ["my activity", "history", "recent activity", "my contributions"],
  },
  {
    title: "My Discussions",
    description: "Open your published discussions and saved drafts.",
    href: "/my-discussions",
    category: "Activity",
    keywords: ["my discussions", "my posts", "drafts", "published discussions"],
  },
  {
    title: "My Replies",
    description: "Review replies you have written across Loombus.",
    href: "/my-replies",
    category: "Activity",
    keywords: ["my replies", "comments", "responses", "replies i wrote"],
  },
  {
    title: "Reading History",
    description: "Return to discussions you recently opened.",
    href: "/reading-history",
    category: "Library",
    keywords: ["reading history", "recently viewed", "history", "read"],
  },
  {
    title: "Onboarding",
    description: "Resume your Loombus setup and account-starting checklist.",
    href: "/onboarding",
    category: "Account",
    keywords: ["onboarding", "setup", "getting started", "start", "checklist"],
  },
  {
    title: "Settings",
    description:
      "Manage appearance, account access, privacy, notifications, and preferences.",
    href: "/settings",
    category: "Account",
    keywords: [
      "settings",
      "appearance",
      "privacy",
      "account",
      "preferences",
      "notifications",
    ],
  },
  {
    title: "Privacy & Security",
    description:
      "Review account privacy, security controls, blocking, and data choices.",
    href: "/privacy-security",
    category: "Account",
    keywords: [
      "privacy security",
      "security",
      "privacy controls",
      "account protection",
      "data",
    ],
  },
  {
    title: "Blocked Users",
    description: "Review and manage the members you have blocked.",
    href: "/blocked-users",
    category: "Safety",
    keywords: ["blocked users", "blocks", "unblock", "safety", "privacy"],
  },
  {
    title: "Loombus Guide",
    description:
      "Learn how Loombus knowledge, Search, Rooms, Local, real-world directories, subscriptions, and safety tools work.",
    href: "/settings/guide",
    category: "Help",
    keywords: [
      "guide",
      "help",
      "how to use",
      "instructions",
      "signal",
      "rooms",
      "search",
      "local",
      "services",
      "marketplace",
    ],
  },
  {
    title: "AI Usage",
    description:
      "Review AI usage, limits, feature buckets, cached outputs, and recent AI-assisted activity.",
    href: "/ai-usage",
    category: "AI",
    keywords: ["ai", "ai usage", "limits", "meter", "cached", "premium ai"],
  },
  {
    title: "Premium",
    description:
      "Review subscription options, AI access, Video Context limits, and supported Premium benefits.",
    href: "/premium",
    category: "Subscription",
    keywords: [
      "premium",
      "subscription",
      "upgrade",
      "plans",
      "premium plus",
      "video context",
    ],
  },
  {
    title: "Loombus Labs",
    description: "Request, vote on, and review experimental Loombus features.",
    href: "/labs",
    category: "Build",
    keywords: ["labs", "features", "requests", "vote", "experimental"],
  },
  {
    title: "Support",
    description:
      "Search complete Loombus help and submit a structured support request.",
    href: "/support",
    category: "Help",
    keywords: [
      "support",
      "help",
      "contact",
      "problem",
      "request",
      "billing",
      "safety",
      "accessibility",
    ],
  },
  {
    title: "About Loombus",
    description:
      "Read how Loombus connects knowledge, private communities, AI, Local, services, commerce, and Signal over noise.",
    href: "/about",
    category: "Reference",
    keywords: [
      "about",
      "about loombus",
      "purpose",
      "mission",
      "signal over noise",
      "everything knowledge platform",
    ],
  },
  {
    title: "Community Guidelines",
    description:
      "Review conduct rules for discussions, Rooms, messages, files, listings, jobs, services, events, AI, and platform integrity.",
    href: "/guidelines",
    category: "Safety",
    keywords: ["guidelines", "community guidelines", "rules", "standards", "conduct"],
  },
  {
    title: "Safety",
    description:
      "Review emergency limits, reporting, blocking, account security, minors, files, Local, transactions, and real-world safety.",
    href: "/safety",
    category: "Safety",
    keywords: ["safety", "reporting", "blocking", "moderation", "protection"],
  },
  {
    title: "Privacy Policy",
    description:
      "Review how Loombus handles account, Room, message, search, AI, location, listing, billing, device, and support information.",
    href: "/privacy",
    category: "Legal",
    keywords: ["privacy", "privacy policy", "data", "information", "rights"],
  },
  {
    title: "Cookie Use",
    description:
      "Review cookies, authentication tokens, browser storage, native application storage, and related technologies.",
    href: "/cookies",
    category: "Legal",
    keywords: [
      "cookies",
      "cookie use",
      "browser storage",
      "session",
      "tokens",
      "local storage",
    ],
  },
  {
    title: "Terms of Service",
    description:
      "Review the terms governing the complete Loombus service and user-to-user activity.",
    href: "/terms",
    category: "Legal",
    keywords: ["terms", "terms of service", "agreement", "legal", "conditions"],
  },
  {
    title: "Refund Policy",
    description:
      "Review web and app-store cancellation, refund, billing-dispute, and add-on rules.",
    href: "/refunds",
    category: "Legal",
    keywords: [
      "refund",
      "refund policy",
      "cancellation",
      "billing",
      "apple",
      "app store",
    ],
  },
  {
    title: "Copyright / DMCA",
    description:
      "Review copyright notice, takedown, counter-notice, and repeat-infringer procedures.",
    href: "/dmca",
    category: "Legal",
    keywords: [
      "copyright",
      "dmca",
      "infringement",
      "takedown",
      "counter notice",
      "rights",
    ],
  },
  {
    title: "Accessibility",
    description:
      "Review keyboard, screen-reader, zoom, contrast, media, file, mobile, and support accessibility information.",
    href: "/accessibility",
    category: "Reference",
    keywords: [
      "accessibility",
      "accessible",
      "disability",
      "support",
      "accommodation",
      "keyboard",
      "screen reader",
      "zoom",
    ],
  },
  {
    title: "Download Loombus",
    description: "Open the Loombus app download page.",
    href: "/download",
    category: "Reference",
    keywords: ["download", "app", "ios", "android", "app store", "google play"],
  },
];
