import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Native build artifacts generated by Capacitor/Xcode/Gradle:
    "android/**/build/**",
    "ios/**/build/**",
    "ios/App/DerivedData/**",
  ]),
]);

export default eslintConfig;
