import type { MetadataRoute } from "next";

const siteUrl = "https://loombus.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/about",
          "/download",
          "/support",
          "/guidelines",
          "/safety",
          "/privacy",
          "/terms",
          "/cookies",
          "/refunds",
          "/dmca",
          "/accessibility",
          "/login",
          "/signup",
          "/icon.png",
          "/apple-icon.png",
          "/opengraph-image.png",
          "/manifest.webmanifest",
        ],
        disallow: [
          "/admin",
          "/admin/",
          "/api",
          "/api/",
          "/home",
          "/dashboard",
          "/create",
          "/create/",
          "/saved",
          "/saved/",
          "/notifications",
          "/notifications/",
          "/messages",
          "/messages/",
          "/profile",
          "/profile/",
          "/my-activity",
          "/my-discussions",
          "/my-replies",
          "/reading-history",
          "/stickies",
          "/following",
          "/settings",
          "/settings/",
          "/privacy-security",
          "/ai-usage",
          "/blocked-users",
          "/rooms",
          "/rooms/",
          "/onboarding",
          "/age-gate",
          "/account-access",
          "/reset-password",
          "/unsubscribe",
          "/u/",
          "/auth/",
        ],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
