"use client";

import { BookOpen, FileClock } from "lucide-react";
import { useState } from "react";
import { Empty, formatDate } from "@/components/room-expansion-ui";

export function KnowledgeView({ data, manifest, working, action }) {
  const articles = Array.isArray(data) ? data : [];
  const [editingId, setEditingId] = useState("");
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [category, setCategory] = useState("General");
  const [tags, setTags] = useState("");
  function edit(article) { setEditingId(article.id); setTitle(article.title); setContent(article.body); setCategory(article.metadata?.category || "General"); setTags((article.metadata?.tags ?? []).join(", ")); }
  return <div className="room-expansion-grid">{manifest.access?.canManage ? <form className="room-expansion-form" onSubmit={(event) => event.preventDefault()}><h3>{editingId ? "Edit knowledge article" : "Create knowledge article"}</h3><label><span>Title</span><input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label><span>Article</span><textarea rows={9} value={content} onChange={(event) => setContent(event.target.value)} /></label><div className="room-expansion-form-grid"><label><span>Category</span><input value={category} onChange={(event) => setCategory(event.target.value)} /></label><label><span>Tags</span><input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="policy, onboarding" /></label></div><div className="room-expansion-inline-actions"><button type="button" disabled={working || !title.trim()} onClick={() => void action({ action: "save_knowledge", recordId: editingId || null, title, content, category, tags: tags.split(","), publish: false }, "Draft saved.")}><FileClock aria-hidden="true" /> Save draft</button><button type="button" disabled={working || !title.trim()} onClick={() => void action({ action: "save_knowledge", recordId: editingId || null, title, content, category, tags: tags.split(","), publish: true }, "Article published.")}><BookOpen aria-hidden="true" /> Publish</button></div></form> : null}<div className="room-expansion-list">{articles.length ? articles.map((article) => <article key={article.id} className="room-expansion-card"><header><div><span>{article.status}</span><small>{article.metadata?.category || "General"}</small></div>{manifest.access?.canManage ? <button type="button" onClick={() => edit(article)}>Edit</button> : null}</header><h3>{article.title}</h3><p>{article.body}</p>{article.metadata?.tags?.length ? <div className="room-expansion-tags">{article.metadata.tags.map((tag) => <span key={tag}>{tag}</span>)}</div> : null}{manifest.access?.canManage && article.versions?.length ? <details className="room-expansion-details"><summary>{article.versions.length} versions</summary>{article.versions.map((version) => <div key={version.id} className="room-expansion-version"><span>Version {version.versionNumber} · {formatDate(version.createdAt)}</span><button type="button" onClick={() => void action({ action: "restore_knowledge", recordId: article.id, versionId: version.id }, "Knowledge version restored.")}>Restore</button></div>)}</details> : null}</article>) : <Empty Icon={BookOpen} title="No knowledge articles" text="Publish searchable guidance with drafts, tags, and automatic version history." />}</div></div>;
}
