"use client";

import Link from "next/link";
import { ChevronRight, Loader2, LockKeyhole, RefreshCw, Search, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";

export type SavedViewOption<T extends string> = { value: T; label: string; count: number };

export function SavedHeader({ eyebrow, title, copy, browseHref, browseLabel, browseIcon, loading, refresh }: { eyebrow: string; title: string; copy: string; browseHref: string; browseLabel: string; browseIcon: ReactNode; loading: boolean; refresh: () => void }) {
  return <header className="mb-6 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
    <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[color:var(--loombus-gold)]">{eyebrow}</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">{title}</h1><p className="mt-3 text-base leading-7 text-[color:var(--loombus-text-muted)]">{copy}</p></div>
    <div className="flex flex-wrap gap-2"><Link href={browseHref} className="inline-flex h-12 items-center gap-2 rounded-2xl border border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)] px-4 text-sm font-semibold shadow-sm transition hover:border-[color:var(--loombus-gold)]">{browseIcon}{browseLabel}</Link><button type="button" onClick={refresh} disabled={loading} className="inline-flex h-12 items-center gap-2 rounded-2xl bg-[color:var(--loombus-gold)] px-4 text-sm font-semibold text-[color:var(--loombus-gold-contrast)] transition hover:opacity-90 disabled:opacity-60"><RefreshCw size={16} className={loading ? "animate-spin" : ""}/>Refresh</button></div>
  </header>;
}

export function SavedMetrics({ items }: { items: Array<{ label: string; value: number }> }) {
  return <section className="mb-6 grid gap-3 sm:grid-cols-3" aria-label="Saved items summary">{items.map((item, index) => <article key={item.label} className={`rounded-[1.4rem] border p-4 shadow-sm ${index === 0 ? "border-[color:var(--loombus-gold)] bg-[color:var(--loombus-cream)] text-[color:var(--loombus-cream-contrast)] dark:bg-[color:var(--loombus-gold-soft)] dark:text-[color:var(--loombus-text)]" : "border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)]"}`}><span className={`text-xs font-bold uppercase tracking-[0.18em] ${index === 0 ? "text-[color:var(--loombus-gold)]" : "text-[color:var(--loombus-text-muted)]"}`}>{item.label}</span><strong className="mt-2 block text-3xl tracking-[-0.04em]">{item.value}</strong></article>)}</section>;
}

export function SavedControls<T extends string>({ query, setQuery, placeholder, view, setView, options }: { query: string; setQuery: (value: string) => void; placeholder: string; view: T; setView: (value: T) => void; options: SavedViewOption<T>[] }) {
  return <><label className="relative block"><span className="sr-only">{placeholder}</span><Search className="pointer-events-none absolute left-5 top-1/2 h-5 w-5 -translate-y-1/2 text-[color:var(--loombus-text-subtle)]"/><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} className="h-14 w-full rounded-2xl border border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)] pl-14 pr-5 text-base outline-none shadow-sm transition placeholder:text-[color:var(--loombus-text-subtle)] focus:border-[color:var(--loombus-gold)] focus:ring-4 focus:ring-[color:var(--loombus-gold-soft)]"/></label><nav className="my-4 flex gap-2 overflow-x-auto pb-1" aria-label="Saved item views">{options.map((option) => <button key={option.value} type="button" onClick={() => setView(option.value)} aria-current={view === option.value ? "page" : undefined} className={`shrink-0 rounded-full border px-4 py-2.5 text-sm font-semibold shadow-sm transition ${view === option.value ? "border-[color:var(--loombus-gold)] bg-[color:var(--loombus-cream)] text-[color:var(--loombus-cream-contrast)] dark:bg-[color:var(--loombus-gold-soft)] dark:text-[color:var(--loombus-gold)]" : "border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)] hover:border-[color:var(--loombus-gold)]"}`}>{option.label}<span className="ml-1 text-xs opacity-70">{option.count}</span></button>)}</nav></>;
}

export function SavedLoading({ label }: { label: string }) { return <section className="rounded-[1.75rem] border border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)] p-10 text-center text-[color:var(--loombus-text-muted)] shadow-xl shadow-black/10"><Loader2 className="mx-auto animate-spin text-[color:var(--loombus-gold)]" size={28}/><p className="mt-3">{label}</p></section>; }

export function SavedEmpty({ icon, title, copy, action }: { icon: ReactNode; title: string; copy: string; action: ReactNode }) { return <section className="rounded-[1.75rem] border border-dashed border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)] p-10 text-center shadow-xl shadow-black/10"><span className="mx-auto grid h-12 w-12 place-items-center text-[color:var(--loombus-gold)]">{icon}</span><h2 className="mt-4 text-2xl font-semibold tracking-[-0.035em]">{title}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[color:var(--loombus-text-muted)]">{copy}</p><div className="mt-5">{action}</div></section>; }

export function SavedRail({ privacyCopy, tools, safetyTitle, safetyCopy }: { privacyCopy: string; tools: Array<[string, string]>; safetyTitle: string; safetyCopy: string }) {
  return <aside className="space-y-5 xl:sticky xl:top-28 xl:self-start"><section className="rounded-[1.75rem] border border-[color:var(--loombus-gold)] bg-[color:var(--loombus-cream)] p-5 text-[color:var(--loombus-cream-contrast)] shadow-2xl shadow-black/10 dark:bg-[color:var(--loombus-gold-soft)] dark:text-[color:var(--loombus-text)]"><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-white/60 text-[color:var(--loombus-gold)] dark:bg-black/10"><LockKeyhole className="h-5 w-5"/></span><div><h2 className="font-semibold">Private to your account</h2><p className="mt-1 text-sm leading-6 opacity-80">{privacyCopy}</p></div></div></section><section className="rounded-[1.75rem] border border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)] p-5 shadow-2xl shadow-black/10"><p className="text-xs font-bold uppercase tracking-[0.3em]">Related tools</p><div className="mt-4 space-y-2">{tools.map(([label, href]) => <Link key={href} href={href} className="flex items-center justify-between rounded-2xl bg-[color:var(--loombus-page-bg)] px-4 py-3 text-sm font-semibold transition hover:bg-[color:var(--loombus-surface-muted)]">{label}<ChevronRight className="h-4 w-4 text-[color:var(--loombus-gold)]"/></Link>)}</div></section><section className="rounded-[1.75rem] border border-[color:var(--loombus-border)] bg-[color:var(--loombus-surface)] p-5 shadow-2xl shadow-black/10"><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[color:var(--loombus-cream)] text-[color:var(--loombus-gold)] dark:bg-[color:var(--loombus-gold-soft)]"><ShieldCheck className="h-5 w-5"/></span><div><h3 className="font-semibold">{safetyTitle}</h3><p className="mt-1 text-sm leading-6 text-[color:var(--loombus-text-muted)]">{safetyCopy}</p></div></div></section></aside>;
}
