import Link from "next/link";
import { PageHeader, PageShell, Panel } from "@/components/ui";

const supportEmail = "support@loombus.com";

export default function PrivacyPage() {
  return (
    <PageShell width="lg">
        <Link href="/" className="mb-10 inline-block text-sm text-zinc-500 hover:text-white">
          ← Back to Loombus
        </Link>

      <PageHeader
        eyebrow="Legal"
        title="Privacy Policy"
        description={
          <>
            This Privacy Policy explains how Loombus may collect, use, store,
            disclose, and protect information connected to the platform. By using
            Loombus, creating an account, posting content, using Premium features,
            or contacting support, you agree to this Privacy Policy.
          </>
        }
      />

      <div className="space-y-8 leading-relaxed text-zinc-400">
        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              1. Information We Collect
            </h2>

            <p>
              Loombus may collect information you provide directly, information
              generated by your use of the platform, and information provided by
              third-party services used to operate Loombus.
            </p>

            <ul className="mt-4 list-disc space-y-2 pl-6">
              <li>account information, such as email address, login method, user ID, and authentication status;</li>
              <li>profile information, such as username, display name, avatar, bio, profile settings, and creator/supporter profile details;</li>
              <li>age-safety information, such as date of birth, age band, Teen Safety Mode status, and guardian-required status;</li>
              <li>content you create or interact with, such as discussions, replies, reports, saves, folders, private notes, reading history, follows, blocks, notifications, Labs requests, topic alerts, and discussion attachments;</li>
              <li>Premium or billing-related information, such as subscription tier, entitlement status, usage limits, checkout events, and payment processor status;</li>
              <li>AI-assisted feature information, such as prompts, discussion text, replies, titles, topics, Reality Lenses, tags, generated summaries, key takeaways, rewrites, quality checks, Conversation Maps, Related Ideas, usage events, output ratings, and cached AI outputs;</li>
              <li>technical information, such as device/browser information, session data, cookies, IP-related information, logs, diagnostics, and security events;</li>
              <li>support information, such as messages, screenshots, issue descriptions, and communications sent to support;</li>
              <li>account status information, such as warnings, suspensions, bans, deactivations, deletion requests, enforcement reasons, admin notes, and audit records;</li>
              <li>email preference information, such as welcome email delivery records, digest preferences, unsubscribe tokens, notification settings, and email delivery metadata;</li>
              <li>copyright, DMCA, refund, billing, legal, or rights-related request information submitted through support or contact workflows.</li>
            </ul>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              2. Account Login and Authentication
            </h2>

            <p>
              Loombus supports email login and Google authentication. Email
              sign-in, email confirmation, password-based authentication, and
              Google sign-in are used as Loombus account authentication layers.
              Loombus does not collect biometric templates. Optional device unlock uses your phone’s local biometric or passcode system. Loombus does not currently require legal-name, state-ID, or ID.me-style identity verification for ordinary member access.
              When you sign in through Google, Loombus may receive authentication
              information from Google, such as your email address, account
              identifier, and basic profile information permitted by the sign-in
              process.
            </p>

            <p className="mt-4">
              Authentication services are used to create sessions, verify
              accounts, protect access, detect unauthorized activity, and keep
              logged-in features available only to authorized users.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              3. How We Use Information
            </h2>

            <p>
              Loombus may use collected information to operate, provide, secure,
              personalize, improve, moderate, and support the platform.
            </p>

            <ul className="mt-4 list-disc space-y-2 pl-6">
              <li>create and manage user accounts;</li>
              <li>display profiles, discussions, replies, saves, follows, blocks, and notifications;</li>
              <li>process reports, moderation actions, safety reviews, and admin workflows;</li>
              <li>provide Premium features, subscription status, AI usage limits, and plan access;</li>
              <li>generate, cache, and display AI-assisted outputs when requested or available;</li>
              <li>detect, prevent, and respond to spam, fraud, abuse, misuse, security threats, age-safety issues, teen-safety risks, and policy violations;</li>
              <li>respond to support, accessibility, safety, billing, or account questions;</li>
              <li>measure reliability, diagnose errors, improve performance, and maintain platform infrastructure;</li>
              <li>comply with legal obligations, enforce Loombus terms, and protect Loombus, users, service providers, and the public.</li>
            </ul>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              4. User Content and Visibility
            </h2>

            <p>
              Some information you provide may be visible to other users or to
              the public, depending on the feature. Public or member-visible
              information may include your username, display name, avatar, bio,
              discussions, replies, follower/following relationships, profile
              links, badges, and other visible activity.
            </p>

            <p className="mt-4">
              Do not post private, sensitive, confidential, or third-party
              information that you do not want others to see or that you do not
              have permission to share.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              5. AI-Assisted Features
            </h2>

            <p>
              Loombus may process discussion content, replies, prompts, titles,
              topics, Reality Lenses, tags, and related metadata to provide
              AI-assisted features such as summaries, key takeaways,
              disagreement maps, thread evolution, Conversation Map, Related
              Ideas, reply suggestions, quality checks, or clarity rewrites.
            </p>

            <p className="mt-4">
              AI outputs may be stored, cached, logged, or associated with usage
              events to support Premium limits, reduce duplicate processing,
              improve reliability, and operate the feature. Do not submit
              sensitive personal information, confidential information, legal
              secrets, medical details, financial account details, or information
              you are not authorized to process through AI-assisted tools.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              6. Cookies and Similar Technologies
            </h2>

            <p>
              Loombus may use cookies, browser storage, authentication tokens,
              session storage, or similar technologies to keep users signed in,
              remember account state, protect sessions, support security, and
              operate core platform features.
            </p>

            <p className="mt-4">
              You can manage cookies through your browser settings. Blocking
              required cookies or storage may affect login, account access,
              Premium features, security controls, and platform functionality.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              7. When We Share Information
            </h2>

            <p>
              Loombus may share or disclose information when needed to operate
              the platform, comply with law, protect safety, or use service
              providers.
            </p>

            <ul className="mt-4 list-disc space-y-2 pl-6">
              <li>with hosting, database, authentication, storage, email, analytics, payment, security, and AI service providers;</li>
              <li>with payment processors to handle checkout, subscriptions, billing status, and fraud prevention;</li>
              <li>when required by law, legal process, court order, subpoena, or governmental request;</li>
              <li>to enforce Loombus Terms, investigate violations, protect users, protect Loombus, or respond to safety and security risks;</li>
              <li>as part of a merger, acquisition, financing, restructuring, sale of assets, or transfer of platform operations;</li>
              <li>with your direction, consent, or intentional public use of platform features.</li>
            </ul>

            <p className="mt-4">
              Loombus does not intend to sell personal information to data
              brokers. If Loombus later introduces advertising, analytics,
              marketing, or data-sharing practices that require additional user
              notice, this Privacy Policy should be updated.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              8. Safety, Moderation, and Legal Protection
            </h2>

            <p>
              Loombus may access, review, preserve, use, or disclose information
              if reasonably necessary to investigate abuse, enforce rules,
              prevent spam, respond to reports, protect users, protect minors,
              protect platform integrity, comply with legal obligations, prevent
              fraud, or defend Loombus, its owner, service providers, or users.
            </p>

            <p className="mt-4">
              Reports, moderation decisions, block records, safety reviews,
              platform-operation actions, audit logs, support request records,
              Labs review records, and related metadata may be stored and
              reviewed to protect the platform and users.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              9. Data Retention
            </h2>

            <p>
              Loombus may retain information for as long as reasonably necessary
              to provide the service, maintain accounts, comply with legal
              obligations, resolve disputes, enforce Terms, process payments,
              prevent abuse, preserve safety records, maintain backups, and
              operate platform features.
            </p>

            <p className="mt-4">
              Some content or records may remain in backups, logs, moderation
              records, audit records, legal records, billing records, support
              records, email delivery records, AI usage records, cached systems,
              or security systems for a period of time after deletion or account
              closure. Some information may be retained where required or
              permitted by law, safety, fraud prevention, abuse prevention,
              billing, dispute resolution, intellectual-property review,
              chargeback response, tax/accounting obligations, or platform
              integrity needs.
            </p>

            <p className="mt-4">
              Account deletion requests may be reviewed before final processing
              because public content, moderation history, safety records, billing
              state, audit logs, and legal obligations may require careful
              handling rather than immediate hard deletion.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              10. Your Choices and Controls
            </h2>

            <p>
              You may update certain account and profile information through
              Loombus settings or profile tools. You may choose what you post,
              save, follow, block, report, or display publicly.
            </p>

            <p className="mt-4">
              You may contact Loombus at{" "}
              <a
                href={`mailto:${supportEmail}?subject=Loombus%20Privacy%20Request`}
                className="text-zinc-200 underline-offset-4 hover:underline"
              >
                {supportEmail}
              </a>{" "}
              for privacy-related questions or requests. Loombus may need to
              verify your identity before processing certain requests.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              11. Security
            </h2>

            <p>
              Loombus uses reasonable technical and organizational measures to
              protect the platform. However, no internet service, database,
              authentication system, hosting provider, payment processor, or
              transmission method is perfectly secure. Loombus cannot guarantee
              absolute security.
            </p>

            <p className="mt-4">
              You are responsible for using a strong password, protecting your
              email account, avoiding suspicious links, and keeping your account
              access secure.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              12. Children, Minors, and Teen Safety Mode
            </h2>

            <p>
              Loombus is not intended for children under 13 and does not
              knowingly allow children under 13 to create accounts. Users must
              be at least 13 years old to use Loombus. If Loombus learns that it
              has collected personal information from a child under 13 without
              appropriate consent, Loombus may delete the information, restrict
              the account, preserve records needed for safety or legal
              compliance, and take other appropriate action.
            </p>

            <p className="mt-4">
              Loombus may collect date of birth to determine whether an account
              is under 13, a teen account, an adult account, or unknown-age until
              age safety is completed. Loombus may use this information to apply
              Teen Safety Mode, block under-13 access, limit private-message
              access, route unknown-age users to an age-safety gate, and support
              moderation review.
            </p>

            <p className="mt-4">
              Teen Safety Mode may apply additional safety protections to users
              ages 13–17, including stricter private-message checks, teen-related
              safety metadata, and higher-priority review signals for certain
              blocked or warned events. Loombus does not display exact date of
              birth publicly.
            </p>

            <p className="mt-4">
              Parents or guardians who believe a child under 13 provided
              information to Loombus, or who have safety concerns involving a
              teen account, may contact support for review.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              13. International Users
            </h2>

            <p>
              Loombus is operated from the United States. If you access Loombus
              from outside the United States, you understand that your
              information may be processed, stored, or transferred in the United
              States or other locations where Loombus or its service providers
              operate.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              14. Changes to This Privacy Policy
            </h2>

            <p>
              Loombus may update this Privacy Policy from time to time. The
              updated version will apply when posted or when otherwise
              communicated. Your continued use of Loombus after an update means
              you accept the updated policy.
            </p>
        </Panel>

        <Panel>
            <h2 className="mb-4 text-2xl font-semibold text-white">
              15. Contact
            </h2>

            <p>
              Privacy questions may be sent to{" "}
              <a
                href={`mailto:${supportEmail}?subject=Loombus%20Privacy%20Question`}
                className="text-zinc-200 underline-offset-4 hover:underline"
              >
                {supportEmail}
              </a>
              .
            </p>

            <p className="mt-4 text-sm text-zinc-600">
              Effective date: May 22, 2026
            </p>
        </Panel>
      </div>
    </PageShell>
  );
}
