import type { NavigationItem } from "./types";

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: "home",
    label: "Home",
    href: "/home",
    description: "Return to the authenticated Loombus home surface.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "bottom"],
    keywords: ["home", "dashboard", "start", "overview"],
    requiresAuth: true,
  },
  {
    id: "discussions",
    label: "Discussions",
    href: "/discussions",
    description: "Open the main Loombus discussion feed.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "bottom"],
    keywords: ["discussions", "feed", "threads", "signal", "conversation"],
    requiresAuth: true,
  },
  {
    id: "create",
    label: "Create",
    href: "/create",
    description: "Start a focused discussion.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "bottom"],
    keywords: ["create", "post", "discussion", "write", "composer", "publish", "draft"],
    requiresAuth: true,
  },
  {
    id: "search",
    label: "Search",
    href: "/search",
    description: "Search pages, discussions, people, saved items, and topics.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "utility"],
    keywords: ["search", "find", "discover", "lookup", "topics"],
    requiresAuth: true,
  },
  {
    id: "people",
    label: "People",
    href: "/people",
    description: "Find contributors, profiles, followers, and people you follow.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "bottom"],
    keywords: ["people", "members", "profiles", "contributors", "followers", "following"],
    requiresAuth: true,
  },
  {
    id: "following",
    label: "Following",
    href: "/following",
    description: "View people and activity connected to your following graph.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["following", "followers", "network", "people"],
    requiresAuth: true,
  },
  {
    id: "saved",
    label: "Saved",
    href: "/saved",
    description: "Return to saved discussions, notes, folders, and bookmarks.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "bottom"],
    keywords: ["saved", "bookmarks", "folders", "notes", "private notes", "library"],
    requiresAuth: true,
  },
  {
    id: "messages",
    label: "Messages",
    href: "/messages",
    description: "Open private conversations with mutual followers.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["messages", "chat", "dm", "inbox", "private conversations"],
    requiresAuth: true,
  },
  {
    id: "notifications",
    label: "Notifications",
    href: "/notifications",
    description: "Review replies, follows, alerts, and platform activity.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "bottom"],
    keywords: ["notifications", "alerts", "replies", "follows", "activity"],
    requiresAuth: true,
  },
  {
    id: "rooms",
    label: "Rooms",
    href: "/rooms",
    description: "Open private rooms, communities, and shared workspaces.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "bottom"],
    keywords: ["rooms", "private rooms", "communities", "workspace", "groups"],
    requiresAuth: true,
  },
  {
    id: "stickies",
    label: "Stickies",
    href: "/stickies",
    description: "Open pinned notes, topics, people, and saved ideas.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["stickies", "pins", "pinned", "notes", "workspace"],
    requiresAuth: true,
  },
  {
    id: "labs",
    label: "Labs",
    href: "/labs",
    description: "Request, vote on, and review experimental platform features.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "utility"],
    keywords: ["labs", "features", "requests", "vote", "experimental"],
    requiresAuth: true,
  },
  {
    id: "profile",
    label: "Profile",
    href: "/profile",
    description: "Manage your public profile and identity.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "utility"],
    keywords: ["profile", "account", "identity", "avatar", "bio"],
    requiresAuth: true,
  },
  {
    id: "my-activity",
    label: "My Activity",
    href: "/my-activity",
    description: "Review your discussions, replies, saves, and recent activity.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["my activity", "activity", "history", "recent activity"],
    requiresAuth: true,
  },
  {
    id: "my-discussions",
    label: "My Discussions",
    href: "/my-discussions",
    description: "Open the discussions you started or manage your drafts.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["my discussions", "my posts", "my threads", "drafts", "published discussions"],
    requiresAuth: true,
  },
  {
    id: "my-replies",
    label: "My Replies",
    href: "/my-replies",
    description: "Open the replies you have written across Loombus discussions.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["my replies", "my comments", "responses", "replies i wrote"],
    requiresAuth: true,
  },
  {
    id: "reading-history",
    label: "Reading History",
    href: "/reading-history",
    description: "Return to discussions you recently viewed.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["reading history", "recently viewed", "history", "read"],
    requiresAuth: true,
  },
  {
    id: "premium",
    label: "Premium",
    href: "/premium",
    description: "Review subscription options and premium platform access.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["premium", "subscription", "upgrade", "premium plus", "plans"],
    requiresAuth: true,
  },
  {
    id: "settings",
    label: "Settings",
    href: "/settings",
    description: "Manage appearance, account access, legal links, and platform preferences.",
    audience: "authenticated",
    surfaces: ["desktop", "mobile", "utility"],
    keywords: ["settings", "appearance", "account", "privacy", "terms", "preferences"],
    requiresAuth: true,
  },
  {
    id: "support",
    label: "Support",
    href: "/support",
    description: "Get help with Loombus.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["support", "help", "contact", "issue"],
    requiresAuth: true,
  },
  {
    id: "privacy-security",
    label: "Privacy & Security",
    href: "/privacy-security",
    description: "Review privacy, security, and safety controls.",
    audience: "authenticated",
    surfaces: ["mobile", "utility"],
    keywords: ["privacy", "security", "safety", "controls"],
    requiresAuth: true,
  },
  {
    id: "admin",
    label: "Admin",
    href: "/admin",
    description: "Open Loombus administration tools.",
    audience: "admin",
    surfaces: ["desktop", "mobile", "admin"],
    keywords: ["admin", "moderation", "reports", "users", "support"],
    requiresAuth: true,
    requiresAdmin: true,
  },
];

export function getNavigationItemsForSurface(surface: NavigationItem["surfaces"][number]) {
  return NAVIGATION_ITEMS.filter((item) => item.surfaces.includes(surface));
}

export function getNavigationItemById(id: NavigationItem["id"]) {
  return NAVIGATION_ITEMS.find((item) => item.id === id) ?? null;
}
