-- Member privacy, discoverability, viewer identity, and private-account follow requests.
-- Apply once after the existing Discussion audience migrations.

begin;

create table if not exists public.member_privacy_settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  private_account boolean not null default false,
  discoverable boolean not null default true,
  show_view_identity boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.follow_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  target_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint follow_requests_not_self check (requester_id <> target_id),
  constraint follow_requests_status_check check (
    status in ('pending', 'accepted', 'declined', 'cancelled')
  )
);

create unique index if not exists follow_requests_one_pending_pair_idx
  on public.follow_requests(requester_id, target_id)
  where status = 'pending';
create index if not exists follow_requests_target_pending_idx
  on public.follow_requests(target_id, created_at desc)
  where status = 'pending';
create index if not exists follow_requests_requester_pending_idx
  on public.follow_requests(requester_id, created_at desc)
  where status = 'pending';

alter table public.discussion_views
  add column if not exists identity_visible boolean not null default true;

create table if not exists public.profile_views (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  viewer_id uuid not null references public.profiles(id) on delete cascade,
  identity_visible boolean not null default true,
  viewed_at timestamptz not null default now(),
  constraint profile_views_not_self check (profile_id <> viewer_id)
);

create index if not exists profile_views_profile_recent_idx
  on public.profile_views(profile_id, viewed_at desc);
create index if not exists profile_views_viewer_recent_idx
  on public.profile_views(viewer_id, viewed_at desc);
create index if not exists discussion_views_author_lookup_idx
  on public.discussion_views(discussion_id, viewed_at desc);

create or replace function public.touch_member_privacy_settings_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists touch_member_privacy_settings_updated_at_trigger
  on public.member_privacy_settings;
create trigger touch_member_privacy_settings_updated_at_trigger
before update on public.member_privacy_settings
for each row execute function public.touch_member_privacy_settings_updated_at();

insert into public.member_privacy_settings (user_id)
select profile.id
from public.profiles profile
on conflict (user_id) do nothing;

alter table public.member_privacy_settings enable row level security;
alter table public.follow_requests enable row level security;
alter table public.profile_views enable row level security;

drop policy if exists member_privacy_settings_owner_select
  on public.member_privacy_settings;
create policy member_privacy_settings_owner_select
on public.member_privacy_settings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists member_privacy_settings_owner_insert
  on public.member_privacy_settings;
create policy member_privacy_settings_owner_insert
on public.member_privacy_settings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists member_privacy_settings_owner_update
  on public.member_privacy_settings;
create policy member_privacy_settings_owner_update
on public.member_privacy_settings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists follow_requests_participant_select
  on public.follow_requests;
create policy follow_requests_participant_select
on public.follow_requests
for select
to authenticated
using (auth.uid() = requester_id or auth.uid() = target_id);

-- All writes flow through authenticated server routes so state transitions,
-- block checks, notifications, and rate limits cannot be bypassed.
revoke insert, update, delete on table public.follow_requests from authenticated;
revoke insert, update, delete on table public.profile_views from authenticated;

grant select, insert, update on table public.member_privacy_settings to authenticated;
grant select on table public.follow_requests to authenticated;

create or replace function public.can_view_member_profile(
  p_profile_id uuid,
  p_viewer_id uuid
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
set row_security = off
as $$
declare
  privacy_row public.member_privacy_settings%rowtype;
  viewer_is_admin boolean := false;
begin
  if p_profile_id is null or p_viewer_id is null then
    return false;
  end if;

  if p_profile_id = p_viewer_id then
    return true;
  end if;

  select coalesce(profile.is_admin, false)
  into viewer_is_admin
  from public.profiles profile
  where profile.id = p_viewer_id;

  if viewer_is_admin then
    return true;
  end if;

  if exists (
    select 1
    from public.user_blocks block
    where (
      block.blocker_id = p_profile_id and block.blocked_id = p_viewer_id
    ) or (
      block.blocker_id = p_viewer_id and block.blocked_id = p_profile_id
    )
  ) then
    return false;
  end if;

  select *
  into privacy_row
  from public.member_privacy_settings privacy
  where privacy.user_id = p_profile_id;

  if not found or privacy_row.private_account is false then
    return true;
  end if;

  return exists (
    select 1
    from public.follows relationship
    where relationship.follower_id = p_viewer_id
      and relationship.following_id = p_profile_id
  );
end;
$$;

revoke all on function public.touch_member_privacy_settings_updated_at()
  from public, anon, authenticated;
revoke all on function public.can_view_member_profile(uuid, uuid)
  from public, anon;
grant execute on function public.can_view_member_profile(uuid, uuid)
  to authenticated;

notify pgrst, 'reload schema';

commit;
