"use client";

import { ProfileAvatar, getProfileDisplayName } from "@/components/profile-avatar";
import { normalizePublicText } from "@/lib/public-text";
import { supabase } from "@/lib/supabase/client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Reply = { id:string; body:string; discussion_id:string; created_at:string; edited_at?:string|null; edit_count?:number|null };
type Discussion = { id:string; title:string; topic:string; deleted_at:string|null };
type Profile = { full_name:string|null; username:string|null; avatar_url:string|null };
type Sort = "newest"|"oldest"|"engagement";
type ReactionRow = { reply_id:string; reaction_type:string };

function formatDate(value:string){return new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));}

export default function MyRepliesV2Client(){
 const [replies,setReplies]=useState<Reply[]>([]),[discussions,setDiscussions]=useState<Record<string,Discussion>>({}),[profile,setProfile]=useState<Profile|null>(null);
 const [reactionCounts,setReactionCounts]=useState<Record<string,number>>({}),[query,setQuery]=useState(""),[topic,setTopic]=useState("all"),[sort,setSort]=useState<Sort>("newest"),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 useEffect(()=>{let alive=true;(async()=>{try{
  const {data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user){location.href="/login";return}
  const [profileResult,replyResult]=await Promise.all([
   supabase.from("profiles").select("full_name,username,avatar_url").eq("id",user.id).maybeSingle(),
   supabase.from("replies").select("id,body,discussion_id,created_at,edited_at,edit_count").eq("user_id",user.id).is("deleted_at",null).order("created_at",{ascending:false})
  ]);
  if(profileResult.error)throw profileResult.error;if(replyResult.error)throw replyResult.error;
  const rows=(replyResult.data??[]) as Reply[],ids=[...new Set(rows.map(r=>r.discussion_id))];let map:Record<string,Discussion>={},counts:Record<string,number>={};
  if(ids.length){const [discussionResult,reactionResult]=await Promise.all([
   supabase.from("discussions").select("id,title,topic,deleted_at").in("id",ids),
   supabase.from("reply_reactions").select("reply_id,reaction_type").in("reply_id",rows.map(r=>r.id))
  ]);
  for(const d of discussionResult.data??[])map[d.id]=d as Discussion;
  for(const reaction of (reactionResult.data??[]) as ReactionRow[])counts[reaction.reply_id]=(counts[reaction.reply_id]??0)+1;
  }
  if(!alive)return;setProfile((profileResult.data??null) as Profile|null);setReplies(rows);setDiscussions(map);setReactionCounts(counts);
 }catch(error){console.error("Unable to load My Replies",error);if(alive)setNotice("Your replies could not be loaded. Refresh and try again.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const topics=useMemo(()=>[...new Set(replies.map(r=>discussions[r.discussion_id]?.topic).filter(Boolean) as string[])].sort(),[replies,discussions]);
 const totalReactions=Object.values(reactionCounts).reduce((sum,count)=>sum+count,0),available=replies.filter(r=>!discussions[r.discussion_id]?.deleted_at).length,edited=replies.filter(r=>r.edited_at).length;
 const results=useMemo(()=>{const needle=query.trim().toLowerCase();return replies.filter(r=>{const d=discussions[r.discussion_id];const matchesTopic=topic==="all"||d?.topic===topic;const text=[r.body,d?.title,d?.topic].filter(Boolean).join(" ").toLowerCase();return matchesTopic&&(!needle||text.includes(needle))}).sort((a,b)=>sort==="engagement"?(reactionCounts[b.id]??0)-(reactionCounts[a.id]??0)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime():sort==="oldest"?new Date(a.created_at).getTime()-new Date(b.created_at).getTime():new Date(b.created_at).getTime()-new Date(a.created_at).getTime())},[replies,discussions,query,topic,sort,reactionCounts]);
 if(loading)return <main className="min-h-screen bg-[var(--loombus-page-bg)] px-4 py-10 text-[var(--loombus-text)]"><div className="mx-auto max-w-6xl rounded-[2rem] border border-[var(--loombus-border)] bg-[var(--loombus-surface)] p-8"><p className="text-sm font-bold uppercase tracking-[.22em] text-[var(--loombus-gold)]">My Replies</p><h1 className="mt-3 text-4xl font-bold">Building your Signal history…</h1></div></main>;
 return <main className="min-h-screen bg-[var(--loombus-page-bg)] px-4 pb-24 pt-4 text-[var(--loombus-text)] sm:px-6 sm:py-10 lg:px-8"><div className="mx-auto max-w-7xl space-y-5">
  <header className="rounded-[2rem] border border-[var(--loombus-border)] bg-[var(--loombus-surface)] p-6 shadow-2xl shadow-black/10 sm:p-9"><div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-[var(--loombus-gold)]">Signal Hub</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-[-.045em] sm:text-6xl">See where your perspective added Signal.</h1><p className="mt-4 max-w-2xl leading-7 text-[var(--loombus-text-muted)]">Search your replies, revisit the discussion context, and understand which replies earned reactions.</p></div><div className="flex items-center gap-3 rounded-2xl border border-[var(--loombus-border)] bg-[var(--loombus-surface-strong)] p-3"><ProfileAvatar profile={profile} size="xl"/><div><p className="text-xs uppercase tracking-[.16em] text-[var(--loombus-text-subtle)]">Member</p><p className="mt-1 font-semibold">{getProfileDisplayName(profile)}</p></div></div></div><div className="mt-6 flex flex-wrap gap-3"><Link href="/discussions" className="rounded-full bg-[var(--loombus-gold-strong)] px-5 py-3 text-sm font-semibold text-[var(--loombus-gold-contrast)]">Join a discussion</Link><Link href="/my-activity" className="rounded-full border border-[var(--loombus-border)] px-5 py-3 text-sm font-semibold">Open My Activity</Link></div></header>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total replies",replies.length],["Available threads",available],["Reactions received",totalReactions],["Edited replies",edited]].map(([label,value])=><div key={label} className="rounded-2xl border border-[var(--loombus-border)] bg-[var(--loombus-surface)] p-4 sm:p-5"><p className="text-xs uppercase tracking-[.14em] text-[var(--loombus-text-subtle)]">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</section>
  {notice&&<div className="rounded-2xl border border-[var(--loombus-border)] bg-[var(--loombus-surface)] px-4 py-3 text-sm text-[var(--loombus-text-muted)]">{notice}</div>}
  <section className="rounded-[1.75rem] border border-[var(--loombus-border)] bg-[var(--loombus-surface)] p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_14rem_14rem]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reply text, discussion title, or topic" className="min-h-12 rounded-2xl border border-[var(--loombus-border)] bg-[var(--loombus-page-bg)] px-4 outline-none focus:border-[var(--loombus-gold)]"/><select value={topic} onChange={e=>setTopic(e.target.value)} className="min-h-12 rounded-2xl border border-[var(--loombus-border)] bg-[var(--loombus-page-bg)] px-4"><option value="all">All topics</option>{topics.map(t=><option key={t} value={t}>{t}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="min-h-12 rounded-2xl border border-[var(--loombus-border)] bg-[var(--loombus-page-bg)] px-4"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="engagement">Most engaged</option></select></div></section>
  <div className="flex items-center justify-between"><div><p className="font-semibold">{results.length} {results.length===1?"reply":"replies"}</p><p className="mt-1 text-xs text-[var(--loombus-text-subtle)]">Edit and delete controls remain inside the parent discussion.</p></div>{(query||topic!=="all")&&<button onClick={()=>{setQuery("");setTopic("all")}} className="rounded-full border border-[var(--loombus-border)] px-4 py-2 text-sm">Reset</button>}</div>
  {replies.length===0?<section className="rounded-[2rem] border border-[var(--loombus-border)] bg-[var(--loombus-surface)] p-7 sm:p-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--loombus-gold)]">Add Signal</p><h2 className="mt-3 text-3xl font-bold">Your reply history will appear here.</h2><p className="mt-3 max-w-2xl text-[var(--loombus-text-muted)]">Add context, experience, evidence, or a sharper question to an existing discussion.</p><Link href="/discussions" className="mt-6 inline-flex rounded-full bg-[var(--loombus-gold-strong)] px-5 py-3 font-semibold text-[var(--loombus-gold-contrast)]">Browse discussions</Link></section>:results.length===0?<section className="rounded-[2rem] border border-[var(--loombus-border)] bg-[var(--loombus-surface)] p-8"><h2 className="text-2xl font-bold">No replies match this view.</h2><p className="mt-3 text-[var(--loombus-text-muted)]">Broaden the search or reset the topic filter.</p></section>:<section className="space-y-3">{results.map(reply=>{const d=discussions[reply.discussion_id],availableThread=Boolean(d&&!d.deleted_at);return <article key={reply.id} className="rounded-[1.6rem] border border-[var(--loombus-border)] bg-[var(--loombus-surface)] p-5 transition hover:border-[var(--loombus-gold)] sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[var(--loombus-gold-soft)] px-3 py-1 text-xs font-bold text-[var(--loombus-gold)]">{d?.topic??"Discussion"}</span>{!availableThread&&<span className="rounded-full border border-[var(--loombus-border)] px-3 py-1 text-xs text-[var(--loombus-text-subtle)]">Unavailable</span>}</div><h2 className="mt-3 text-xl font-bold sm:text-2xl">{d?.title?normalizePublicText(d.title):"Discussion unavailable"}</h2></div><div className="shrink-0 text-sm text-[var(--loombus-text-subtle)]">{formatDate(reply.created_at)}</div></div><p className="mt-4 whitespace-pre-wrap leading-7 text-[var(--loombus-text-muted)]">{normalizePublicText(reply.body)}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--loombus-border)] pt-4"><div className="flex gap-3 text-sm text-[var(--loombus-text-subtle)]"><span>{reactionCounts[reply.id]??0} reactions</span>{reply.edited_at&&<span>Edited {formatDate(reply.edited_at)}</span>}</div>{availableThread?<Link href={`/discussions/${reply.discussion_id}#replies`} className="rounded-full bg-[var(--loombus-gold-strong)] px-4 py-2 text-sm font-semibold text-[var(--loombus-gold-contrast)]">Open and manage</Link>:<span className="text-sm text-[var(--loombus-text-subtle)]">Parent discussion unavailable</span>}</div></article>})}</section>}
 </div></main>
}
