"use client";

import { ProfileAvatar, getProfileDisplayName } from "@/components/profile-avatar";
import { normalizePublicText } from "@/lib/public-text";
import { supabase } from "@/lib/supabase/client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Reply = { id:string; body:string; discussion_id:string; created_at:string; edited_at?:string|null; edit_count?:number|null };
type Discussion = { id:string; title:string; topic:string; deleted_at:string|null };
type Profile = { full_name:string|null; username:string|null; avatar_url:string|null };
type Sort = "newest"|"oldest"|"engagement";
type ReactionRow = { reply_id:string; reaction_type:string };

function formatDate(value:string){return new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));}

export default function MyRepliesV2Client(){
 const [replies,setReplies]=useState<Reply[]>([]),[discussions,setDiscussions]=useState<Record<string,Discussion>>({}),[profile,setProfile]=useState<Profile|null>(null);
 const [reactionCounts,setReactionCounts]=useState<Record<string,number>>({}),[query,setQuery]=useState(""),[topic,setTopic]=useState("all"),[sort,setSort]=useState<Sort>("newest"),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 useEffect(()=>{let alive=true;(async()=>{try{
  const {data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user){location.href="/login";return}
  const [profileResult,replyResult]=await Promise.all([
   supabase.from("profiles").select("full_name,username,avatar_url").eq("id",user.id).maybeSingle(),
   supabase.from("replies").select("id,body,discussion_id,created_at,edited_at,edit_count").eq("user_id",user.id).is("deleted_at",null).order("created_at",{ascending:false})
  ]);
  if(profileResult.error)throw profileResult.error;if(replyResult.error)throw replyResult.error;
  const rows=(replyResult.data??[]) as Reply[],ids=[...new Set(rows.map(r=>r.discussion_id))];let map:Record<string,Discussion>={},counts:Record<string,number>={};
  if(ids.length){const [discussionResult,reactionResult]=await Promise.all([
   supabase.from("discussions").select("id,title,topic,deleted_at").in("id",ids),
   supabase.from("reply_reactions").select("reply_id,reaction_type").in("reply_id",rows.map(r=>r.id))
  ]);
  for(const d of discussionResult.data??[])map[d.id]=d as Discussion;
  for(const reaction of (reactionResult.data??[]) as ReactionRow[])counts[reaction.reply_id]=(counts[reaction.reply_id]??0)+1;
  }
  if(!alive)return;setProfile((profileResult.data??null) as Profile|null);setReplies(rows);setDiscussions(map);setReactionCounts(counts);
 }catch(error){console.error("Unable to load My Replies",error);if(alive)setNotice("Your replies could not be loaded. Refresh and try again.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const topics=useMemo(()=>[...new Set(replies.map(r=>discussions[r.discussion_id]?.topic).filter(Boolean) as string[])].sort(),[replies,discussions]);
 const totalReactions=Object.values(reactionCounts).reduce((sum,count)=>sum+count,0),available=replies.filter(r=>!discussions[r.discussion_id]?.deleted_at).length,edited=replies.filter(r=>r.edited_at).length;
 const results=useMemo(()=>{const needle=query.trim().toLowerCase();return replies.filter(r=>{const d=discussions[r.discussion_id];const matchesTopic=topic==="all"||d?.topic===topic;const text=[r.body,d?.title,d?.topic].filter(Boolean).join(" ").toLowerCase();return matchesTopic&&(!needle||text.includes(needle))}).sort((a,b)=>sort==="engagement"?(reactionCounts[b.id]??0)-(reactionCounts[a.id]??0)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime():sort==="oldest"?new Date(a.created_at).getTime()-new Date(b.created_at).getTime():new Date(b.created_at).getTime()-new Date(a.created_at).getTime())},[replies,discussions,query,topic,sort,reactionCounts]);
 if(loading)return <main className="min-h-screen bg-[var(--loombus-page-bg)] px-4 py-10 text-[var(--loombus-text)]"><div className="mx-auto max-w-6xl border-y border-[var(--loombus-border)] py-8"><p className="text-sm font-bold uppercase tracking-[.22em] text-[var(--loombus-gold)]">My Replies</p><h1 className="mt-3 text-4xl font-bold">Building your Signal history…</h1></div></main>;
 return <main className="min-h-screen bg-[var(--loombus-page-bg)] px-4 pb-24 pt-4 text-[var(--loombus-text)] sm:px-6 sm:py-10 lg:px-8"><div className="mx-auto max-w-7xl">
  <header className="border-b border-[var(--loombus-border)] pb-8"><div className="grid gap-7 lg:grid-cols-[minmax(0,1fr)_18rem] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-[var(--loombus-gold)]">Signal Hub</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-[-.045em] sm:text-6xl">See where your perspective added Signal.</h1><p className="mt-4 max-w-2xl leading-7 text-[var(--loombus-text-muted)]">Search your replies, revisit the discussion context, and understand which replies earned reactions.</p></div><div className="border-l-2 border-[var(--loombus-gold)] pl-4"><div className="flex items-center gap-3"><ProfileAvatar profile={profile} size="xl"/><div><p className="text-xs uppercase tracking-[.16em] text-[var(--loombus-text-subtle)]">Member</p><p className="mt-1 font-semibold">{getProfileDisplayName(profile)}</p></div></div></div></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2"><Link href="/discussions" className="inline-flex min-h-11 items-center border-b-2 border-[var(--loombus-gold)] px-1 py-2 text-sm font-semibold transition-colors hover:text-[var(--loombus-gold)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--loombus-gold)]">Join a discussion</Link><Link href="/my-activity" className="inline-flex min-h-11 items-center border-b border-[var(--loombus-border)] px-1 py-2 text-sm font-semibold transition-colors hover:border-[var(--loombus-gold)] hover:text-[var(--loombus-gold)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--loombus-gold)]">Open My Activity</Link></div></header>
  <section className="grid border-b border-[var(--loombus-border)] sm:grid-cols-2 lg:grid-cols-4">{[["Total replies",replies.length],["Available threads",available],["Reactions received",totalReactions],["Edited replies",edited]].map(([label,value],index)=><div key={label} className={`border-b border-[var(--loombus-border)] py-5 sm:px-5 lg:border-b-0 ${index>0?"sm:border-l":""} ${index%2===0?"sm:pl-0 lg:pl-5":""}`}><p className="text-xs uppercase tracking-[.14em] text-[var(--loombus-text-subtle)]">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</section>
  {notice&&<div className="border-b border-[var(--loombus-border)] py-4 text-sm text-[var(--loombus-text-muted)]" role="status">{notice}</div>}
  <section className="border-b border-[var(--loombus-border)] py-6"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_14rem_14rem]"><label><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--loombus-text-subtle)]">Search replies</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reply text, discussion title, or topic" className="min-h-12 w-full border-0 border-b border-[var(--loombus-border)] bg-transparent px-1 text-sm outline-none transition-colors placeholder:text-[var(--loombus-text-subtle)] focus:border-[var(--loombus-gold)] focus-visible:ring-0"/></label><label><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--loombus-text-subtle)]">Topic</span><select value={topic} onChange={e=>setTopic(e.target.value)} className="min-h-12 w-full border-0 border-b border-[var(--loombus-border)] bg-transparent px-1 text-sm outline-none focus:border-[var(--loombus-gold)] focus-visible:ring-0"><option value="all">All topics</option>{topics.map(t=><option key={t} value={t}>{t}</option>)}</select></label><label><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--loombus-text-subtle)]">Sort</span><select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="min-h-12 w-full border-0 border-b border-[var(--loombus-border)] bg-transparent px-1 text-sm outline-none focus:border-[var(--loombus-gold)] focus-visible:ring-0"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="engagement">Most engaged</option></select></label></div></section>
  <div className="flex flex-wrap items-center justify-between gap-4 border-b border-[var(--loombus-border)] py-5"><div><p className="font-semibold">{results.length} {results.length===1?"reply":"replies"}</p><p className="mt-1 text-xs text-[var(--loombus-text-subtle)]">Edit and delete controls remain inside the parent discussion.</p></div>{(query||topic!=="all")&&<button onClick={()=>{setQuery("");setTopic("all")}} className="min-h-11 border-b border-[var(--loombus-border)] px-1 py-2 text-sm transition-colors hover:border-[var(--loombus-gold)] hover:text-[var(--loombus-gold)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--loombus-gold)]">Reset</button>}</div>
  {replies.length===0?<section className="border-b border-[var(--loombus-border)] py-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--loombus-gold)]">Add Signal</p><h2 className="mt-3 text-3xl font-bold">Your reply history will appear here.</h2><p className="mt-3 max-w-2xl text-[var(--loombus-text-muted)]">Add context, experience, evidence, or a sharper question to an existing discussion.</p><Link href="/discussions" className="mt-6 inline-flex min-h-11 items-center border-b-2 border-[var(--loombus-gold)] px-1 py-2 font-semibold transition-colors hover:text-[var(--loombus-gold)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--loombus-gold)]">Browse discussions</Link></section>:results.length===0?<section className="border-b border-[var(--loombus-border)] py-10"><h2 className="text-2xl font-bold">No replies match this view.</h2><p className="mt-3 text-[var(--loombus-text-muted)]">Broaden the search or reset the topic filter.</p></section>:<section>{results.map(reply=>{const d=discussions[reply.discussion_id],availableThread=Boolean(d&&!d.deleted_at);return <article key={reply.id} className="grid gap-4 border-b border-[var(--loombus-border)] py-6 transition-colors hover:border-[var(--loombus-gold)] sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs font-bold uppercase tracking-[.14em] text-[var(--loombus-text-subtle)]"><span className="text-[var(--loombus-gold)]">{d?.topic??"Discussion"}</span>{!availableThread&&<span>· Unavailable</span>}</div><h2 className="mt-3 text-xl font-bold sm:text-2xl">{d?.title?normalizePublicText(d.title):"Discussion unavailable"}</h2><p className="mt-4 whitespace-pre-wrap leading-7 text-[var(--loombus-text-muted)]">{normalizePublicText(reply.body)}</p><div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-[var(--loombus-border)] pt-4 text-sm text-[var(--loombus-text-subtle)]"><span>{reactionCounts[reply.id]??0} reactions</span>{reply.edited_at&&<span>Edited {formatDate(reply.edited_at)}</span>}{availableThread?<Link href={`/discussions/${reply.discussion_id}#replies`} className="ml-auto inline-flex min-h-11 items-center border-b-2 border-[var(--loombus-gold)] px-1 py-2 font-semibold text-[var(--loombus-text)] transition-colors hover:text-[var(--loombus-gold)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--loombus-gold)]">Open and manage</Link>:<span className="ml-auto">Parent discussion unavailable</span>}</div></div><time className="text-sm text-[var(--loombus-text-subtle)]">{formatDate(reply.created_at)}</time></article>})}</section>}
 </div></main>
}
